DROP TABLE IF EXISTS BEFRIENDED_TOYS;

CREATE TABLE BEFRIENDED_TOYS
(
UUID VARCHAR2(100) NOT NULL,
MAJOR NUMBER(15) NOT NULL,
MINOR NUMBER(15) NOT NULL,
TOY_NAME VARCHAR2(100),
IMAGE_BASE64 VARCHAR2(32767)
);

INSERT INTO BEFRIENDED_TOYS(UUID,MAJOR,MINOR,TOY_NAME,IMAGE_BASE64) VALUES('a',1,2,'Spyro',null);
INSERT INTO BEFRIENDED_TOYS(UUID,MAJOR,MINOR,TOY_NAME,IMAGE_BASE64) VALUES('b',3,4,'Trigger Happy',null);
INSERT INTO BEFRIENDED_TOYS(UUID,MAJOR,MINOR,TOY_NAME,IMAGE_BASE64) VALUES('c',5,6,'Eruptor',null);
